# Generated by Django 5.2.4 on 2025-07-31 06:42

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subscribers', models.PositiveIntegerField(default=0)),
                ('revenue', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('views', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='업로드 날짜')),
                ('duration', models.DurationField(default=datetime.timedelta(0), verbose_name='영상 길이')),
                ('status', models.CharField(choices=[('Public', '공개'), ('Private', '비공개'), ('Unlisted', '일부 공개')], default='Private', max_length=10, verbose_name='공개 상태')),
                ('thumbnail_url', models.URLField(blank=True, help_text='영상 썸네일 이미지 URL', null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='youtube.accountinfo')),
            ],
        ),
    ]
