# c:\Pyprojects\dashboard\youtube\migrations\0002_populate_initial_data.py
# Generated by Django 5.2.4 on 2025-07-31 10:00

from django.db import migrations
from django.utils import timezone
import datetime


def create_initial_data(apps, schema_editor):
    """
    초기 AccountInfo 및 Video 데이터를 생성합니다.
    """
    AccountInfo = apps.get_model('youtube', 'AccountInfo')
    Video = apps.get_model('youtube', 'Video')

    # 1. 계정 정보 생성 (없을 경우에만)
    my_account, created = AccountInfo.objects.get_or_create(
        name='MyTube Studio Channel',
        defaults={
            'subscribers': 123000,
            'revenue': 4567
        }
    )

    # 2. 비디오 데이터 생성 (없을 경우에만)
    videos_to_create = [
        {
            'title': '나의 첫 브이로그', 'status': 'Public', 'views': 10234, 'likes': 850,
            'uploaded_at': timezone.now(), 'duration': datetime.timedelta(seconds=305),
            'thumbnail_url': 'https://i.ytimg.com/vi/v1_y_9Lg-wA/hqdefault.jpg'
        },
        {
            'title': 'Django 튜토리얼 #1 - 시작하기', 'status': 'Unlisted', 'views': 8910, 'likes': 1200,
            'uploaded_at': timezone.now() - datetime.timedelta(days=3), 'duration': datetime.timedelta(seconds=1230),
            'thumbnail_url': 'https://i.ytimg.com/vi/F5mRW0jo-U4/hqdefault.jpg'
        },
        {
            'title': '요리 레시피: 김치찌개', 'status': 'Private', 'views': 540, 'likes': 50,
            'uploaded_at': timezone.now() - datetime.timedelta(days=7), 'duration': datetime.timedelta(seconds=480),
            'thumbnail_url': 'https://i.ytimg.com/vi/rV22aA_a-sI/hqdefault.jpg'
        },
        {
            'title': '게임 하이라이트 #25', 'status': 'Public', 'views': 25430, 'likes': 2100,
            'uploaded_at': timezone.now() - datetime.timedelta(days=10), 'duration': datetime.timedelta(seconds=615),
            'thumbnail_url': 'https://i.ytimg.com/vi/s4p-t_T5LhI/hqdefault.jpg'
        },
    ]

    for video_data in videos_to_create:
        Video.objects.get_or_create(
            account=my_account,
            title=video_data['title'],
            defaults=video_data
        )


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
